### PR TITLE
Resolve NPE on import of calibrated product data

### LINKED ISSUE #1: Null pointer Exception when attempting to import NovaSAR data
I get a null pointer exception at line 373 of NovaSARProductDirectory.java when trying to import a product

double calConstant = imageAttributes.getElement("CalibrationConstant").getAttributeDouble("CalibrationConstant", 1.0);

I fixed this locally and can submit in a pull request.

### PR DESCRIPTION
**Pull request by DanseMacabre**
Resolves #1 

@marpet will this also be built against 6.0.x for the SNAP 6.0 and pushed to the updatecenters?

I've tested this fix locally also.

### CODE REVIEW

**Comment by DanseMacabre** [comment]
~~Actually, although this resolves the NPE, I didn't check it was grabbing the correct cal constant! I'll fix and re-submit.~~

FYI - this does, in fact, grab the correct Cal constant and therefore this comment should be ignored.

**Comment by DanseMacabre** [comment]
@marpet I've just checked this now, and it does indeed grab the correct calibration constant.

**Comment by sposerina** [comment]
Was the issue resolved?

**Comment by DanseMacabre** [comment]
This change resolves the issue and includes the correct calibration in the metadata. Needs Marco to accept this request before he builds a fixed version and releases it.

**Pull request merged**
